#ifndef _GENERALDEFINES_INCLUDE
#define _GENERALDEFINES_INCLUDE

#define SHOW_HIT_BOXES

#define SCREEN_X 0
#define SCREEN_Y 0

#define INIT_PLAYER_X_TILES 7
#define INIT_PLAYER_Y_TILES 2

#define JUMP_ANGLE_STEP 1
#define JUMP_HEIGHT 96
#define FALL_STEP 1

#define TIME_PER_FRAME 1000.f / 60.f // Approx. 60 fps

#define SCREEN_WIDTH 1270
#define SCREEN_HEIGHT 720

#endif // _GENERALDEFINES_INCLUDE
