#ifndef _GENERALDEFINES_INCLUDE
#define _GENERALDEFINES_INCLUDE

//#define SHOW_HIT_BOXES

#define SCREEN_X 0
#define SCREEN_Y 0

#define INIT_PLAYER_X_TILES 7
#define INIT_PLAYER_Y_TILES 2

#define JUMP_ANGLE_STEP 1
#define JUMP_HEIGHT 96
#define FALL_STEP 1

#define TIME_PER_FRAME 1000.f / 60.f // Approx. 60 fps

#define COORD_VIEW_LIMIT_X 450.0f
#define COORD_VIEW_LIMIT_Y 300.0f

#define SCREEN_WIDTH 1270
#define SCREEN_HEIGHT 720
#define PI 3.141592653589f

#endif // _GENERALDEFINES_INCLUDE
